Feature/cakephp challenge2
MunehiroMachida/quelcode-cakephp pull request #3
Opened 2020-09-03 01:40 UTC by MunehiroMachida

cakephp課題2の実装しました。よろしくお願いします。
[DB定義書]
https://docs.google.com/spreadsheets/d/1a906kLftI_i9MDrDzgHmbfUcBmR0RVtVq-D3xMzh7V8/edit?usp=sharing
[詳細設計]
https://docs.google.com/document/d/1y8y52JgIkX45fqLeEw0OQQSPyJx4uMJ1zPl6b4H-9b0/edit?usp=sharing

2020-09-03 02:52 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +				$count = count($this->Bidinfo->find('all')->toArray());
変数を使ってDB接続処理を減らしましょう
```suggestion
				$count = count($bidinfo_array);
```

2020-09-03 03:02 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/home.ctp
> +					}
```suggestion
					$is_ratings = false;
					for ($j = 0; $j <= count($ratings); $j++) {
						if (($ratings[$j]['biditem_id'] === $buyer_status_biditem_id) && ($ratings[$j]['rater'] === $buyer_id)) {
							$is_ratings = true;
							break;
						}
					}
```

2020-09-03 03:03 UTC, Yuzunoha requested changes

2020-09-03 03:03 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/home2.ctp
> +							$is_ratings = false;
ここも $is_ratings = false; は一回で済みますね！

2020-09-03 03:06 UTC, Yuzunoha requested changes

2020-09-03 03:06 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Ratings/add.ctp
> +</div>
ファイルの最終行で改行しましょう！今回のPRで差分が出てるファイルについては全て末尾に改行があるか確認してください～。触ってないファイルについては対応不要です。

2020-09-03 03:18 UTC, Yuzunoha commented
落札者側から既存のメッセージング画面 http://localhost:10080/auction/msg/1 に飛ぶリンクが無いですね！メッセージング画面へのリンクを復活させてください～。リンクを増やせばよいと思います。

案内表示 `落札者とのメッセージ | 落札者が情報を入力するまでお待ちください | お届け先 | お届け先を入力してください` はレビューした中でもトップクラスの分かりやすさでよいです！

![image](https://user-images.githubusercontent.com/22877094/92067267-d331cb80-edde-11ea-80cb-08286d0c1428.png)

2020-09-03 03:23 UTC, Yuzunoha commented
出品者が発送先の住所(落札者が入力した住所)を閲覧できないっぽいので、
出品者が住所を閲覧した上で発送完了ボタンを押せるようにしてください

2020-09-03 05:22 UTC, Yuzunoha commented
コミットが細かく分かれていてよい！！

2020-09-03 05:43 UTC, Yuzunoha commented
出品者が発送完了ボタンを押す前に、落札者が入力した名前、電話番号、住所が全て閲覧できるようにしてください

2020-09-03 07:01 UTC, Yuzunoha commented
脆弱性を発見しました。

http://localhost:10080/auction/buyerinfo?biditem_id=324
などクエリパラメタにでたらめな商品idを入れても住所が登録できてしまいますね！
出品者の住所表示は先勝ちなので困ったことになります。

http://localhost:10080/auction/buyerinfo?biditem_id=324
のように存在しない商品idが指定された場合はindexにリダイレクトさせましょう。

また商品idが存在しても自分が落札者でない商品の場合もindexにリダイレクトさせましょう。

商品idが存在しかつ自分が落札者でかつ住所を送信済みだった場合は、住所を送信済みですのメッセージと送信済みの住所を表示しましょう。

2020-09-03 07:01 UTC, Yuzunoha requested changes
最終確認したところ脆弱性を発見したのでコメントしました！ご確認ください

2020-09-04 03:26 UTC, Yuzunoha commented
>商品idが存在しかつ自分が落札者でかつ住所を送信済みだった場合は、住所を送信済みですのメッセージと送信済みの住所を表示しましょう。

以前のコメントしたこちらが未対応のようですね！確認をお願いします！！

要するに落札者が何度も住所を送信できないようにしましょう。

2020-09-05 01:12 UTC, Yuzunoha commented
すみません説明不足でした。

>送信済みの住所を表示しましょう

とコメントしている個所は全て名前と電話番号と住所をセットで表示してください！住所の表示が必要な個所は名前と電話番号の表示も必要です


![image](https://user-images.githubusercontent.com/22877094/92293595-b5d83b00-ef5f-11ea-887a-494e89e92efb.png)

2020-09-05 01:18 UTC, Yuzunoha commented
既にアドバイスしているはずですが、ブラウザからリンクを削除するだけではガードしたことになりません。

http://localhost:10080/auction/home

に住所の入力画面へのリンクが無くても、ブラウザの履歴から

localhost:10080/auction/buyerinfo?biditem_id=6

にアクセス出来てしまいます。したがって

localhost:10080/auction/buyerinfo?biditem_id=6

のコントローラで

>1つの商品に対して落札者が何度も住所を送信できないように

するガードを行ってください。





localhost:10080/auction/buyerinfo?biditem_id=6

2020-09-05 11:50 UTC, MunehiroMachida commented
> 1つの商品に対して落札者が何度も住所を送信できないように
>するガードを行ってください。

こちら、評価する際も履歴からアクセスできてしまっていましたので
同じようにfor文を使って修正しました。

2020-09-07 05:40 UTC, Yuzunoha commented
http://localhost:10080/ratings/add?biditem_id=9&target=2&rater=1
のパスで、クエリパラメタを

書き中

2020-09-07 06:08 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +		if ($judgment === false || $buyer_status_judgment === true) {
$judgmentがfalseである、または$buyer_status_judgmentがtrueである

という判定のロジックの場合

変数名の〇〇judgment はその値がtrue/falseだと何を表現するのかが分からないですね！

同じ理由で開発現場では
〇〇judgment 〇〇check 〇〇flug
という「その値がtrue/falseだと何なのかが分からない」ネーミングはレビューでNGです。変えましょう！！

一例ですが is〇〇 とか 〇〇isError といった名前がよいです。

2020-09-07 06:09 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/home.ctp
> +<h6><?= $this->Html->link(__('出品情報に移動 >>'), ['action' => 'home2']) ?></h6>
また進入禁止マークが出ているので末尾で改行してください。他のファイルも末尾の改行を確認をお願いします。

![image](https://user-images.githubusercontent.com/22877094/92353846-1f04ad80-f11c-11ea-9dda-650f531ebb6c.png)

2020-09-08 05:46 UTC, Yuzunoha commented
評価の送信において下記の不正が出来てしまうので、ログインユーザをチェックする処理を入れてください

・落札者が出品者に成り代わって自分への評価を送信する
・出品者が落札者に成り代わって自分への評価を送信する

2020-09-08 06:36 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/RatingsController.php
> +        }
$is_rating (これはレーティングである) という変数名では何を表すのか分からないので変数名NGです！
せめて何を表すのかソースコードにコメントを書いてください。

このガードは既にレビューが登録済みならリダイレクトするという事でしょうが、フラグを導入すると複雑になるのでこのように早期リターンにしましょう。

```suggestion
        for ($i = 0; $i < count($ratings); $i++) {
            if ($ratings[$i]["biditem_id"] === intval($_GET["biditem_id"]) && $ratings[$i]["target"] === intval($_GET["target"]) && $ratings[$i]["rater"] === intval($_GET["rater"])) {

                return $this->redirect(['action' => '../auction']);
            }
        }
```

2020-09-08 06:48 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/RatingsController.php
> +        }
ここも難解なのでフラグを無くしましょう

```suggestion
        if ((intval($_GET["target"]) === $user_id && intval($_GET["rater"]) === $buyer_id) || (intval($_GET["target"]) === $buyer_id && intval($_GET["rater"]) === $user_id)) {
            /* pass */
        } else {
            return $this->redirect(['action' => '../auction']);
        }
```

2020-09-08 07:08 UTC, Yuzunoha commented
すみません、僕のレビューがぬるかったです。
評価機能のガードで `$this->Auth` を使ったログインユーザの突合せをしていないため、hiddenタグを書き換えられると他のユーザに成り代わって評価を送信し放題ですね。

$this->Auth でログインユーザが出品者にか落札者を判定するようにしてください。
それに伴いクエリパラメタやhiddenタグでユーザidを送信する処理は全て不要なので削除してください。


書き中

2020-09-08 07:18 UTC, Yuzunoha commented
追伸

ソースコードの処理を解説するコメントを入れてください！！

2020-09-11 07:22 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +		if ($query_parameter_isError === false || $is_buyer_status_id === true) {
〇〇isError(〇〇がエラーである) は エラーが起こったときにtrueになるべき変数名ですが、現在は意味が逆になっていますね！変数名もしくはbooleanの値を意味が通るように修正しましょう

2020-09-11 07:27 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			if ($bidinfo->biditem_id === intval($_GET["biditem_id"]) && $bidinfo->user_id === $this->Auth->user('id')) {
conditionsでuser_idで絞っているためこの比較は常に真になるので不要ですね
```suggestion
			if ($bidinfo->biditem_id === intval($_GET["biditem_id"])) {
```

2020-09-11 07:58 UTC, Yuzunoha commented
それぞれ発送完了と受け取り完了の通知ボタンですが
hiddenタグでitem_idを指定しており、ログインユーザが操作権のある商品かチェックが無いですね！
ブラウザでhiddenタグの値を書き換えられると別の商品に関する発送、受け取りのデータ登録が出来てしまいます。

ブラウザから送信された値は全てphp側で、ログインユーザ $this->Authの情報と照らし合わせましょう！セキュリティ大事です。なりすましを防ぎましょう

![image](https://user-images.githubusercontent.com/22877094/92887362-63ab8400-f44f-11ea-8042-30e883d4713b.png)

2020-09-11 08:04 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$buyer_status_id = (intval($this->request->getData(['buyer'])));
この値がブラウザで書き換えられていないかチェックする

2020-09-11 08:04 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$biditems_id = (intval($this->request->getData(['item'])));
この値がブラウザで書き換えられていないかチェックする

2020-09-11 08:18 UTC, Yuzunoha commented
評価送信のセキュリティ RatingsController->add よいと思います！

このノリで発送連絡、受け取り連絡のセキュリティも確保してください！！

2020-09-14 05:48 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/home.ctp
> +						echo $this->Form->create(null, ['type' => 'post', 'url' => ['controller' => 'Auction', 'auction' => 'home']]);
ここオークションじゃなくてアクションじゃないですか
```suggestion
						echo $this->Form->create(null, ['type' => 'post', 'url' => ['controller' => 'Auction', 'action' => 'home']]);
```

2020-09-14 05:48 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/home2.ctp
> +						echo $this->Form->create(null, ['type' => 'post', 'url' => ['controller' => 'Auction', 'auction' => 'home2']]);
ここもオークションじゃなくてアクションじゃないですか
```suggestion
						echo $this->Form->create(null, ['type' => 'post', 'url' => ['controller' => 'Auction', 'action' => 'home2']]);
```

2020-09-14 05:49 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +					$biditems_id = $biditems[$i]["id"];
後勝ちになってしまうので break; しましょう

2020-09-14 05:53 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +					$buyer_status_id = $buyer_status[$i]["id"];
$buyer_status_id は186行目で上書きされてしまうのでここでサーチしても意味ないですね！

意味のない処理を含めないようにソースコードを見直してください！！

2020-09-14 06:03 UTC, Yuzunoha commented
自分が出品した商品でも、落札者から住所が入力されていない商品も発送完了にできてしまいます。
発送完了リクエストの条件を追加してください。

要は発送完了ボタンが表示される条件を満たした状態で、発送完了ボタンが押されたリクエストが来たかをサーバ側でチェックしましょう。今の条件だと自分が出品した商品は無条件に biditems 'is_sent' => true に出来てしまいます。

2020-09-14 06:10 UTC, Yuzunoha commented
受け取り完了のリクエストも、ctpファイルで受け取り完了ボタンが表示される条件を満たした状態でリクエストが送られてきたかどうかをサーバ側でチェックしてください。

2020-09-14 06:21 UTC, Yuzunoha commented
まずレビュアから指摘された問題を再現してください(例 ブラウザでformを書き換えてリクエストされると自分が落札していない商品を受け取り完了にできてしまう)。

自分の環境で問題が再現しない場合はレビュアに確認してください。レビュアが勘違いしている場合もあるので。

ソースコードを修正し、動作確認して問題が修正されたことを確認したらレビュー依頼してください。

2020-09-17 01:02 UTC, Yuzunoha commented
正常系の操作で落札者が お届け先を入力してください のリンクを踏むとリダイレクトされてしまい住所が入力できない

2020-09-17 03:11 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +		}
(参考)
hitしなかった場合の判定についてですが
$bidinfo_biditem_id に毎回falseを代入するのはしっくりこないので
僕ならこう書くかなあってやつです
issetを使うとよさそうですね
```suggestion
		$countBidinfo = count($bidinfo);
		for ($j = 0; $j < $countBidinfo; $j++) {
			//商品idが落札されているかチェック
			if ($bidinfo[$j]['biditem_id'] === intval($_GET["biditem_id"])) {
				$bidinfo_biditem_id = $bidinfo[$j]['biditem_id'];
				break;
			}
		}
		if (false === isset($bidinfo_biditem_id)) {
			return $this->redirect(['action' => 'index']);
		}
```

2020-09-17 03:50 UTC, Yuzunoha commented
レビューしたら✓
- [ ] 落札者が行う発送先情報の登録のセキュリティ

2020-09-17 04:11 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +		])->toArray();
$bidinfos は未使用ですね。ソースコードの品質向上のため未使用のローカル変数は削除しましょう！

2020-09-17 04:27 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +		$biditems = $this->Biditems->find('all')->toArray(); //出品者
$biditemsは219行目で初期化したのと同名のローカル変数ですね
書き中

2020-09-17 05:10 UTC, Yuzunoha commented
AuctionController->home
チェックが足りず、まだ出品者から発送されていない商品を受け取り完了に出来てしまうようです。ご確認ください。

2020-09-17 05:36 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/RatingsController.php
> +                $entity = $this->request->getData();
ここで取得しているhiddenタグの商品IDをブラウザで書き換えられると、自分が取引に関わった別の商品の評価を複数回送信出来てしまいます。

現状の問題は、商品IDをクエリパラメタとhiddenタグの2カ所から取得していることです。

商品IDはクエリパラメタで渡された値を採用することとし、hiddenタグで商品IDを渡すのは脆弱性となるので廃止しましょう。


![image](https://user-images.githubusercontent.com/22877094/93424428-fbe3b600-f8f2-11ea-9fe3-3b4cfb96a6df.png)

2020-09-18 04:19 UTC, MunehiroMachida commented on html/mycakeapp/src/Controller/RatingsController.php
> +                $entity = $this->request->getData();
> AuctionController->home
> チェックが足りず、まだ出品者から発送されていない商品を受け取り完了に出来てしまうようです。ご確認ください。

```
if (intval($_POST["is_received"]) !== 0) { //ここで受け取り完了のチェック
return $this->redirect(['action' => 'index']);
}
```
このif文を追加してチェックしました。

2020-09-18 04:59 UTC, MunehiroMachida commented on html/mycakeapp/src/Controller/RatingsController.php
> +                $entity = $this->request->getData();
> ここで取得しているhiddenタグの商品IDをブラウザで書き換えられると、自分が取引に関わった別の商品の評価を複数回送信出来てしまいます。
現状の問題は、商品IDをクエリパラメタとhiddenタグの2カ所から取得していることです。
商品IDはクエリパラメタで渡された値を採用することとし、hiddenタグで商品IDを渡すのは脆弱性となるので廃止しましょう。


src/Template/Ratings/add.ctpにif分を追加して商品idとgetの値が違った場合、リダイレクトするようにしました

2020-09-18 07:24 UTC, Yuzunoha commented
発送されていない商品が受け取り完了にできる

2020-09-18 07:29 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			if (intval($_POST["is_received"]) !== 0) { //ここで受け取り完了のチェック
postの値はブラウザで書き換えることができるので、単体で比較しても意味がありません。

2020-09-18 07:33 UTC, Yuzunoha commented
出品者から発送されていない商品を落札者が受け取り完了にできるバグが直っていないのでご確認をお願いします。

2020-09-23 01:04 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			if ($bidinfo_biditem_id === intval($_GET["biditem_id"])) {
(修正不要)
このif文は278~280行目で保障されている内容であり、必ず真になるので不要ですね

2020-09-23 01:47 UTC, Yuzunoha commented
こちらで確認した限りでは、出品者から発送されていない商品を落札者が受け取り完了にできるバグが直っていません。

2020-09-23 09:20 UTC, Yuzunoha commented
正常系の操作で`受け取り完了`ボタンが効かなくなりました。ご確認をお願いします。

2020-09-23 09:25 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +				if ($biditem[$j]["id"] === intval($this->request->getData(['buyer']))) {
ここで $this->request->getData(['buyer']) と一致するbiditem_idをサーチしていますが、$this->request->getData(['buyer']) はbiditem_idではないですね。ご自身の設計をご確認ください。

2020-09-24 01:56 UTC, Yuzunoha commented
自分が出品した商品一覧画面で、まだ落札されていない商品のIDが出なくなりました。
この列はカラム名を商品IDにして、商品IDを出すようにすれば解決すると思います。
![image](https://user-images.githubusercontent.com/22877094/94091799-246c3280-fe54-11ea-9d81-c063896711c4.png)

2020-09-24 05:50 UTC, Yuzunoha approved these changes
OKです！承認しました！！

2020-10-02 06:46 UTC, merged